<?php
#dId,dNom,dBoite
$deckNames=array(
  0=>array('dNom'=>'Héros','dBoite'=>0),
  1=>array('dNom'=>'Rhino','dBoite'=>1),
  2=>array('dNom'=>'Klaw','dBoite'=>1),
  3=>array('dNom'=>'CrossBones','dBoite'=>6),
  4=>array('dNom'=>'Héros','dBoite'=>0),
  5=>array('dNom'=>'Légions d\'Hydra','dBoite'=>1),
  6=>array('dNom'=>'Ingérence En Cours','dBoite'=>7),
  7=>array('dNom'=>'Absorption Électrique','dBoite'=>7),
  8=>array('dNom'=>'Un Immense Gâchis','dBoite'=>7),
  9=>array('dNom'=>'Patrouille D\'Hydra','dBoite'=>6),
  10=>array('dNom'=>'Le siège De L\'Apocalypse','dBoite'=>1),
  11=>array('dNom'=>'Civils Attaqués','dBoite'=>1),
  12=>array('dNom'=>'Les Maîtres Du Mal','dBoite'=>1),
  13=>array('dNom'=>'Alerte à La Bombe','dBoite'=>1),
  14=>array('dNom'=>'Ultron','dBoite'=>1),
  15=>array('dNom'=>'Entreprise à Risques','dBoite'=>7),
  16=>array('dNom'=>'Formule Mutagène','dBoite'=>7),
  17=>array('dNom'=>'Le Compresseur','dBoite'=>8),
  18=>array('dNom'=>'Le Démolisseur','dBoite'=>8),
  19=>array('dNom'=>'Le Bulldozer','dBoite'=>8),
  20=>array('dNom'=>'Le Boulet','dBoite'=>8),
  21=>array('dNom'=>'L\'Homme Absorbant','dBoite'=>6),
  22=>array('dNom'=>'Zola','dBoite'=>6),
  23=>array('dNom'=>'Taskmaster','dBoite'=>6),
  24=>array('dNom'=>'Crâne Rouge','dBoite'=>6),
  25=>array('dNom'=>'Kang','dBoite'=>15),
  26=>array('dNom'=>'Le Maître Du Temps','dBoite'=>15),
  27=>array('dNom'=>'Les Anachronautes','dBoite'=>15),
  28=>array('dNom'=>'Temporel','dBoite'=>15),
  29=>array('dNom'=>'La confrérie des Badoon','dBoite'=>2),
  30=>array('dNom'=>'Nébula','dBoite'=>2),
  31=>array('dNom'=>'Ronan l\Accusateur','dBoite'=>2),
  32=>array('dNom'=>'Artefacts Galactiques','dBoite'=>2),
  33=>array('dNom'=>'Pirates de l\'espace','dBoite'=>2),
  34=>array('dNom'=>'Contrôles du vaisseau','dBoite'=>2),
  35=>array('dNom'=>'Campagne - Défi Standard','dBoite'=>2),
  36=>array('dNom'=>'Traqueur Badoon','dBoite'=>2),
  37=>array('dNom'=>'Campagne - Défi Expert','dBoite'=>2),
  38=>array('dNom'=>'Mâchoire d\'ébène','dBoite'=>22),
  39=>array('dNom'=>'Défense de la tour','dBoite'=>22),
  40=>array('dNom'=>'Thanos','dBoite'=>22),
  41=>array('dNom'=>'Hela','dBoite'=>22),
  42=>array('dNom'=>'Loki','dBoite'=>22),
  43=>array('dNom'=>'L\'ordre Noir','dBoite'=>22),
  44=>array('dNom'=>'Armées du Titan','dBoite'=>22),
  45=>array('dNom'=>'Enfants de Thanos','dBoite'=>22),
  46=>array('dNom'=>'Gant de l\'infini','dBoite'=>22),
  47=>array('dNom'=>'Légions de Hel','dBoite'=>22),
  48=>array('dNom'=>'Géants de glace','dBoite'=>22),
  49=>array('dNom'=>'L\'enchanteresse','dBoite'=>22),
  50=>array('dNom'=>'Basique / Campagne','dBoite'=>22),
  51=>array('dNom'=>'Campagne - Expert','dBoite'=>22),
  52=>array('dNom'=>'The Hood','dBoite'=>26),
  53=>array('dNom'=>'Hommes-bêtes','dBoite'=>26),
  54=>array('dNom'=>'Gang de Crossfire','dBoite'=>26),
  55=>array('dNom'=>'Mister Hyde','dBoite'=>26),
  56=>array('dNom'=>'Sinistre syndicat','dBoite'=>26),
  57=>array('dNom'=>'Etat d\'urgence','dBoite'=>26),
  58=>array('dNom'=>'Les Démolisseurs','dBoite'=>26),
  59=>array('dNom'=>'Fanatique Kree','dBoite'=>23)
);
?>