<?php
  $str=array(
      'adminPwd'=>'Administrative password',
      'gamePass'=>'This game key is',
      'siteAdmin'=>'Site administration',
      'help'=>'Help',
      'rcUsage'=>'Using Remote Champions',
      'bugReport'=>'Report a bug',
      'perPlayer'=>'per player',
      'Foiled'=>'Once foiled',
      #Administration du site
      'restrictedTitle'=>'Restricted access',
      'restricted'=>'Sorry, access to this side of the website is protected by a password...',
      'restrictedBack'=>'Back to the website',
      'Theme'=>'Look and feel',
      'ThemeSelect'=>'Select the global gamescreen look and feel',
      'wip'=>'(Work in progress)',
      'boxesTitle'=>'Game bowes activation',
      'globalParam'=>'server-wide parameter',
      'baseBox'=>'game base box',
      'gamesList'=>'Listing of all games hosted on this server',
      'gamePassAdmin'=>'game key',
      'villain'=>'villain',
      'players'=>'Players',
      'gameDate'=>'Launch date',
      'noVillain'=>'none',
      'noPlayer'=>'none',
      'adminOpenGame'=>'Open',
      'deleteConfirm'=>'This can\'t be undone.\nAre you sure you want to destroy every data about the game',
      'adminDelete'=>'Delete',
      'adminPassChanged'=>'Administrative password successfully changed.',
      'warning'=>'Warning',
      'passwordNotStored'=>'The administrative password is not stored in a reversible way in the server database.<br/>(Ensure to keep it in a safe place and don\'t loose it...)',
      'newAdminPass'=>'New password',
      'checkAdminPass'=>'Check',
      'adminPassNotMatch'=>'Both typed password don\'t match : please check!',
      'adminSaved'=>'Changes saved',
      'adminPublicHelp'=>'If you set your server to "public" the following password will be asked to create every new game.',
      'adminPublicStatus'=>'Public mode is',
      'disabled'=>'Disabled',
      'enabled'=>'Enabled',
      'adminPublicPass6char'=>'The public password needs to be at last 6 characters long !',
      'adminUpdate'=>'Update',
      'gitHubError'=>'gitHub request failure',
      'gitHubVersion'=>'Las gitHub update : Version',
      'adminAgo'=>'ago',
      'months'=>'monthes',
      'days'=>'jours',
      'hours'=>'hours',
      'minutes'=>'minutes',
      'onlineUpdate'=>'online',
      'zipUpdate'=>'using local zip file',
      'updateLaunch'=>'Launch update'

      


  );
?>