<?php
  $str=array(
      'adminPwd'=>'Mot de passe administratif',
      'gamePass'=>'Le mot-clef de cette partie est',
      'siteAdmin'=>'Administration du site',
      'help'=>'Aide',
      'rcUsage'=>'Utilisation de Remote Champions',
      'bugReport'=>'Rapporter un problème',
      'perPlayer'=>'par joueur',
      'Foiled'=>'Une fois déjouée',
      #Administration du site
      'restrictedTitle'=>'Accès restreint',
      'restricted'=>'Désolé, l\'accès à cette partie du site est protégé par un mot de passe...',
      'restrictedBack'=>'Retour au site',
      'Theme'=>'Mise en page',
      'ThemeSelect'=>'Choisir l\'apparence de l\'écran de synthèse du jeu',
      'wip'=>'(En travaux)',
      'boxesTitle'=>'Activation des boites de jeu',
      'globalParam'=>'paramètre global du serveur',
      'baseBox'=>'Boite de base',
      'gamesList'=>'Liste des parties sur le serveur',
      'gamePassAdmin'=>'Clef d\'accès',
      'villain'=>'Méchant',
      'players'=>'Joueurs',
      'gameDate'=>'Créée le',
      'noVillain'=>'aucun',
      'noPlayer'=>'aucun',
      'adminOpenGame'=>'Ouvrir',
      'deleteConfirm'=>'Cette action est irréversible.\nEtes-vous certain(e) de souhaiter détruire les informations de la partie',
      'adminDelete'=>'Supprimer',
      'adminPassChanged'=>'Le mot de passe administratif a été modifié.',
      'warning'=>'Attention',
      'passwordNotStored'=>'Le mot de passe modifié ici n\'est pas stocké en clair sur le serveur.<br/>(Veillez à le conserver en lieu sur et à ne pas le perdre...)',
      'newAdminPass'=>'Nouveau mot de passe',
      'checkAdminPass'=>'Vérification',
      'adminPassNotMatch'=>'Le mot de passe saisi et la vérification ne correspondent pas!',
      'adminSaved'=>'Modifications sauvegardées.',
      'adminPublicHelp'=>'Si vous activez le mode public, le mot de passe ci-dessous sera demandé pour accéder à la création d\'une nouvelle partie.',
      'adminPublicStatus'=>'Le mode public est',
      'disabled'=>'Désactivé',
      'enabled'=>'Activé',
      'adminPublicPass6char'=>'Le mot de passe public doit comporter au moins 6 caractères !',
      'adminUpdate'=>'Mise à jour',
      'gitHubError'=>'Echec de la requête gitHub',
      'gitHubVersion'=>'Dernière mise à jour gitHub : version',
      'adminAgo'=>'il y a',
      'months'=>'mois',
      'days'=>'jours',
      'hours'=>'heures',
      'minutes'=>'minutes',
      'onlineUpdate'=>'Automatique',
      'zipUpdate'=>'Par fichier zip',
      'updateLaunch'=>'Lancer la mise à jour'


  );
?>